# frozen_string_literal: true

require "erb"
require "faraday"

DATA_MODULE_TEMPLATE = <<~ERB
  # frozen_string_literal: true

  # This file is generated by `rake update`.  Do not add your changes here.

  require "set"

  module TLDv
    module Data # rubocop:disable Metrics/ModuleLength
      VERSION = "1.0.<%= iana_version %>"

      TLDS = Set.new(
        %w[<% tlds.each do |tld| %>
          <%= tld -%>
  <% end %>
        ]
      ).freeze
    end
  end
ERB

task :update do
  puts "* fetching TLD database"
  raw_data = Faraday.get("https://data.iana.org/TLD/tlds-alpha-by-domain.txt").body

  puts "* updating data.rb"
  tlds = raw_data
         .split("\n")
         .reject { _1.start_with?("#") }
         .map(&:downcase)
         .sort
  matches = raw_data.match(/# version (?<version>\d+)/i)
  iana_version = matches[:version]

  code = ERB.new(DATA_MODULE_TEMPLATE, trim_mode: "<>-").result_with_hash(
    iana_version:,
    tlds:
  )
  File.open(File.expand_path("../lib/tldv/data.rb", __dir__), "w") do |f|
    f.puts code
  end
end
